services:
  app:
    image: ikergarcia2/museumapp:v1.1
    restart: always
    networks:
      - frontend
    ports:
      - 8080:3000
    volumes:
      - ./MuseumApp/src:/app/src
  worker:
    image: pedroluis95/cloudcomputing:v1
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - 8081:3001
    volumes:
      - ./MuseumWorker/src:/app/src
    environment:
      ARCHIVESTORE_HOST: archivestore

  archivestore:
    image: mongo
    restart: always
    command: --quiet --syslog
    networks:
      - backend
    expose:
      - "27017"
    volumes:
      - archivestore-data:/data/db
      - mongo-config:/data/configdb

volumes:
  archivestore-data:
  mongo-config:

networks:
  frontend:
  backend: